name: Run CI checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name:  TestStore
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx nx affected:test  --base=origin/master --parallel