name: Run CI checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm-install
      - run: npx nx affected --target=build --base=origin/master --parallel
  test:
    runs-on: ubuntu-latest
    name: Testing affected apps
    steps:
       - uses: actions/checkout@v2
         with:
          fetch-depth: 0
       - run: npm-install
       - run: npx nx affected --target=test --base=origin/master --parallel
  lint:
    runs-on: ubuntu-latest
    name: Linting affected apps
    steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - run: npm-install
       - run: npx nx affected --target=lint --base=origin/master --parallel
  e2e:
    runs-on: ubuntu-latest
    name: E2E testing affected apps
    steps:
       - uses: actions/checkout@v2
         with:
          fetch-depth: 0
       - run: npm-install
       - run: npx nx affected --target=e2e --base=origin/master --parallel